---

- name: "configure prometheus." 
  hosts: all
  user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    
  roles:
    - prometheus
